name: release

on: 
  workflow_dispatch:



jobs:
  build_and_publish_to_pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    steps:

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build sdist and wheel
        run: uv build

      - name: Publish to PyPI
        run: uv publish
